services:
  pessoas-desaparecidas-frontend:
    image: pessoas-desaparecidas-mt/frontend

    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    restart: unless-stopped
